# Generated by Django 4.2 on 2024-04-09 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="Article's ID")),
                ('headline', models.TextField(verbose_name='Headline')),
                ('url', models.URLField(verbose_name="Article's Link")),
                ('content', models.TextField(verbose_name="Article's Content")),
                ('image', models.URLField(verbose_name='Image Link')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="Author's ID")),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('profile', models.URLField(max_length=100, verbose_name='Tech Crunch Profile')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name="Category's ID")),
                ('category_name', models.CharField(max_length=50, verbose_name="Category's Name")),
                ('link', models.URLField(max_length=50, verbose_name="Category's Link")),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('word', models.CharField(max_length=255, verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='UserKeywordSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('page_count', models.IntegerField(default=1, verbose_name='Total Pages to Search')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersearch', to='techcrunch.keyword', verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'User Search',
            },
        ),
        migrations.CreateModel(
            name='DailySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('headline', models.TextField(verbose_name='Headline')),
                ('url', models.URLField(verbose_name="Article's Link")),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Is Scraped')),
                ('articles', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailysearch', to='techcrunch.article', verbose_name='Articles')),
            ],
            options={
                'verbose_name': 'Daily Search',
            },
        ),
        migrations.CreateModel(
            name='ArticleSearchByKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('headline', models.TextField(verbose_name='Headline')),
                ('url', models.URLField(verbose_name="Article's Link")),
                ('is_scraped', models.BooleanField(default=False, verbose_name='Is Scraped')),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_search_by_keyword', to='techcrunch.article', verbose_name='Article')),
                ('user_keyword_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_search_by_keyword', to='techcrunch.userkeywordsearch', verbose_name='User Keyword Search')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='techcrunch.author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='article', to='techcrunch.category', verbose_name='Categories'),
        ),
    ]
